name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cuando se haga push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Revisa tu repositorio

      - name: Set up Ruby, Jekyll, and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Usa la versión de Ruby que prefieras

      - name: Install dependencies
        run: |
          gem install jekyll
          gem install bundler
          bundle install

      - name: Build and Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Token generado automáticamente
