name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pages: write

    environment:
      name: github-pages  # Añadir esta línea

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Jekyll and dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build -d _site

      - name: Upload the built site as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
