name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Esto se activará cada vez que hagas un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Versión de Ruby compatible

      - name: Install bundler 2.4.22
        run: gem install bundler -v 2.4.22  # Instalar Bundler

      - name: Install dependencies
        run: |
          bundle install  # Instalar dependencias de Ruby

      - name: Build the site
        run: bundle exec jekyll build  # Aquí puedes cambiar este comando si usas otro generador

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Rama donde se despliega el sitio
          folder: _site     # Carpeta generada por el generador de sitios estáticos
          token: ${{ secrets.GH_TOKEN }}  # Usa el token configurado
